board/myapp/bbs/urls.py
from django.urls import path
from . import views

app_name = 'bbs'

urlpatterns = [
    path('', views.index, name= 'index'),
    path('<int:id>', views.detail, name= 'detail'),
]

board/myapp/myapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('bbs/', include('bbs.urls')),
    path('admin/', admin.site.urls),
]

board/myapp/bbs/models.py
from django.db import models

class Article(models.Model):
    content = models.CharField(max_length=200)

    def __str__(self):
        return self.content

board/myapp/bbs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Article

def index(request):
    articles = Article.objects.all()
    context = {
        'message': 'my bbs',
        'articles': articles,
        }
    return render(request, 'bbs/index.html', context)

def detail(request,id):
    article = get_object_or_404(Article, pk=id)
    context = {
        'message': 'Show Article' + str(id),
        'article': article,
    }
    return render(request, 'bbs/detail.html', context)

board/myapp/bbs/templates/bbs/detail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <title>bbs</title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <style>
            body {padding: 20px;}
        </style>
    </head>
    <body>
        <div class="container">
            <h1 class="mt-4">Hello BBS</h1>
            <div class="mt-4">
                <p>{{ message }}</p>
                <div class="card">
                    <div class="card-body">
                        <p class="card-text">{{ article.content }}</p>
                        <a href='{% url "bbs:index" %}' class="btn btn-primary">一覧</a>
                    </div>
                </div>
            </div>
        </div>

        <!-- Bootstrap JS (optional) -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </body>
</html>

board/myapp/bbs/templates/bbs/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <title>bbs</title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <style>
            body {padding: 20px;}
            .article {margin-bottom: 20px;}
        </style>
    </head>
    <body>
        <div class="container">
            <h1 class="mt-4">Hello BBS</h1>
            <div class="mt-4">
                <p>{{ message }}</p>
                {% for article in articles %}
                <div class="article p-3 bg-light">
                    <p>{{ article.content }}</p>
                    <a href='{% url "bbs:detail" article.id %}' class="btn btn-primary">詳細</a>
                </div>
                {% endfor %}
            </div>
        </div>

        <!-- Bootstrap JS (optional) -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </body>
</html>